services:

  db:
    image: pgvector/pgvector:0.8.0-pg17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8000:80"
    environment:
      # Ollama
      - GENERATION_MODEL_NAME=llama3.2
      - EMBEDDINGS_MODEL_NAME=nomic-embed-text
      - EMBEDDINGS_DIMENSIONS=768

      # Database
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      - db

volumes:
  pgdata:
